-- RESOURCE: https://neovim.io/doc/user/options.html
vim.g.have_nerd_font = false
vim.g.loaded_perl_provider = 0
vim.g.loaded_python3_provider = 0
vim.g.loaded_ruby_provider = 0
vim.o.breakindent = true
vim.o.confirm = true
vim.o.inccommand = 'split'
vim.o.list = true
vim.o.scrolloff = 10
vim.o.showmode = false
vim.o.winborder = 'single'
vim.opt.clipboard = 'unnamedplus'
vim.opt.cursorline = true -- highlight the current line
vim.opt.expandtab = true -- convert tabs to spaces
vim.opt.ignorecase = true -- ignore case in search patterns
vim.opt.list = true
vim.opt.listchars = 'tab:> ,lead:.,trail:.'
vim.opt.mouse = ''
vim.opt.number = true -- set numbered lines
vim.opt.relativenumber = true -- show relative line number
vim.opt.scrolloff = 3 -- minimal number of screen lines to keep above and below the cursor
vim.opt.shiftwidth = 4 -- the number of spaces inserted for each indentation
vim.opt.signcolumn = 'yes' -- always show the sign column, otherwise it would shift the text each time
vim.opt.smartcase = true -- smart case
vim.opt.smartindent = true -- make indenting smarter again
vim.opt.spell = true
vim.opt.spelllang = 'en_us,en_gb'
vim.opt.splitbelow = true -- force all horizontal splits to go below current window
vim.opt.splitright = true -- force all vertical splits to go to the right of current window
vim.opt.swapfile = false -- creates a swapfile
vim.opt.tabstop = 4 -- insert 2 spaces for a tab
vim.opt.undofile = true -- enable persistent undo
